sudo: false

language: node_js

node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - '4.0'
  - '4.1'
  - '4.2'
  - 'stable'

before_install:
  - npm install -g mocha babel browserify

script:
  - npm run unit
  - npm run lint
  - npm run webify
